export const CONNECT_TO_SERVER = 'CONNECT_TO_SERVER';
export type CONNECT_TO_SERVER = typeof CONNECT_TO_SERVER;

export const SEND_TO_SERVER = 'SEND_TO_SERVER';
export type SEND_TO_SERVER = typeof SEND_TO_SERVER;

export const DISCONNECT_FROM_SERVER = 'DISCONNECT_FROM_SERVER';
export type DISCONNECT_FROM_SERVER = typeof DISCONNECT_FROM_SERVER;

export const RECEIVE_FROM_SERVER = 'RECEIVE_FROM_SERVER';
export type RECEIVE_FROM_SERVER = typeof RECEIVE_FROM_SERVER;